#!/bin/bash

# Install HAProxy
sudo apt update
sudo apt install -y haproxy=2.8\*

# Configure HAProxy
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
sudo tee /etc/haproxy/haproxy.cfg > /dev/null <<EOT
global
    daemon
    maxconn 256

defaults
    mode http
    timeout connect 5000ms
    timeout client 50000ms
    timeout server 50000ms

frontend http-in
    bind *:80
    default_backend servers

backend servers
    balance roundrobin
    server 109732-web-01 <web-01-54.152.60.211>:80 check
    server 109732-web-02 <web-02-34.204.81.197>:80 check
EOT

# Restart HAProxy service
sudo service haproxy restart
                                                                               
