#!/usr/bin/env bash
# Installs and setup haproxy

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.8
apt-get -y update
apt-get install -y haproxy=2.8\*

# Backup original config file before attempt modifications
cp  /etc/haproxy/haproxy.cfg  /etc/haproxy/haproxy.cfg-org

# Listen to web1 and web2 servers                                                                                                                                                                                                                                       
echo  "
frontend www-http
   	 bind *:80
   	 mode http
   	 default_backend apache
backend	 apache
	mode http
	 balance roundrobin
   server 109732-web-01 54.152.60.211:80 check
   server 109732-web-02 34.204.81.197:80 check
"  >> /etc/haproxy/haproxy.cfg

service haproxy start                                                                                                    
