#!/usr/bin/env bash
# Script that configures HAproxy in a load balancer
CONFIG="
frontend myfrontend
    bind *:80
    mode http
    default_backend web_servers
backend web_servers
   balance roundrobin
   server 109732-web-01 54.152.60.211:80 check
   server 109732-web-02 34.204.81.197:80 check
"
sudo apt-get -y install software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.8
sudo apt-get -y update
sudo apt-get -y install haproxy=2.8.\*
# Backup original config file before attempt modifications
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup
printf "%s" "$CONFIG" >> /etc/haproxy/haproxy.cfg
sudo service haproxy restart
                                                 
